const productsList = [
    // Drinks
    {id: 'simon_juice', name: 'Simon Juice', category: 'drinks', price: 8},
    {id: 'bi_frutas', name: 'Bi Frutas Tropical', category: 'drinks', price: 10},
    {id: 'mirinda_lemon', name: 'Mirinda Lemon', category: 'drinks', price: 5},
    {id: 'disfruta', name: 'Disfruta', category: 'drinks', price: 5},
    {id: 'mirinda_plus', name: 'Mirinda Plus', category: 'drinks', price: 5},
    {id: 'mirinda_orange', name: 'Mirinda Orange', category: 'drinks', price: 5},
    {id: '7up', name: '7up', category: 'drinks', price: 5},
    {id: 'pepsi', name: 'Pepsi', category: 'drinks', price: 5},
    {id: 'red_bull', name: 'Red Bull', category: 'drinks', price: 20},
    {id: 'energy_drink', name: 'Energy Drink', category: 'drinks', price: 12},
    {id: 'rostoy', name: 'Rostoy Melocoton', category: 'drinks', price: 12},
    {id: 'power_horse', name: 'Power Horse', category: 'drinks', price: 15},
    {id: 'lipton', name: 'Lipton Ice Tea', category: 'drinks', price: 7},
    {id: 'small_water', name: 'Small Water', category: 'drinks', price: 3},
    {id: 'medium_water', name: 'Medium Water', category: 'drinks', price: 5},
    {id: 'black_coffee', name: 'Black Coffee', category: 'drinks', price: 10},
    {id: 'milk_coffee', name: 'Milk Coffee', category: 'drinks', price: 12},
    {id: 'chocolate_milk', name: 'Chocolate Milk', category: 'drinks', price: 12},
    {id: 'nescafe', name: 'Nescafe', category: 'drinks', price: 10},
    {id: 'tea', name: 'Tea', category: 'drinks', price: 10},

    // Chips
    {id: 'leader_chili', name: 'Leader Chips Chili', category: 'chips', price: 5},
    {id: 'leader_cheese', name: 'Leader Chips Cheese', category: 'chips', price: 5},
    {id: 'leader_potato', name: 'Leader Chips Potato', category: 'chips', price: 5},
    {id: 'leader_kebab', name: 'Leader Chips Kebab', category: 'chips', price: 5},
    {id: 'leader_sel', name: 'Leader Chips Sel', category: 'chips', price: 5},
    {id: 'conikos_barbacoa', name: 'Conikos Barbacoa', category: 'chips', price: 5},
    {id: 'conikos_chili', name: 'Conikos Chili', category: 'chips', price: 5},
    {id: 'conikos_cheese', name: 'Conikos Cheese', category: 'chips', price: 5},
    {id: 'cheetos_red', name: 'Cheetos Red', category: 'chips', price: 5},
    {id: 'cheetos_green', name: 'Cheetos Green', category: 'chips', price: 5},
    {id: 'pringles', name: 'Pringles', category: 'chips', price: 12},

    // Sweets
    {id: 'choco_prince', name: 'Choco Prince', category: 'sweets', price: 5},
    {id: 'wafer_mix', name: 'Wafer Mix Chocolate', category: 'sweets', price: 5},
    {id: 'milka_wafer', name: 'Milka Choco Wafer', category: 'sweets', price: 5},
    {id: 'nutella_biscuits', name: 'Nutella Biscuits', category: 'sweets', price: 8},
    {id: 'kinder_cards', name: 'Kinder Cards', category: 'sweets', price: 8},
    {id: 'mm_chocolate', name: "M&M's Chocolate", category: 'sweets', price: 8},
    {id: 'mm_peanut', name: "M&M's Peanut", category: 'sweets', price: 8},
    {id: 'oreo', name: 'Oreo', category: 'sweets', price: 5},
    {id: 'kinder_bueno', name: 'Kinder Bueno', category: 'sweets', price: 10},
    {id: 'bounty', name: 'Bounty', category: 'sweets', price: 10},
    {id: 'lion', name: 'Lion', category: 'sweets', price: 8},
    {id: 'kitkat', name: 'KitKat', category: 'sweets', price: 8},
    {id: 'kitkat_chunky', name: 'KitKat Chunky', category: 'sweets', price: 8},
    {id: 'mini_kitkat', name: 'Mini KitKat', category: 'sweets', price: 4},
    {id: 'mars', name: 'Mars', category: 'sweets', price: 10},
    {id: 'snickers', name: 'Snickers', category: 'sweets', price: 10},

    // Candy
    {id: 'fini_liquid', name: 'Fini Boom Liquid', category: 'candy', price: 1},
    {id: 'fini_vampire', name: 'Fini Boom Vampire', category: 'candy', price: 1},
    {id: 'toffee', name: 'Toffee Candies', category: 'candy', price: 1},
    {id: 'trident', name: 'Trident', category: 'candy', price: 1},
    {id: 'clorets', name: 'Clorets', category: 'candy', price: 1},
    {id: 'bim_bom', name: 'Bim Bom Candies', category: 'candy', price: 1},
    {id: 'fizzy_boom', name: 'Fizzy Boom Candies', category: 'candy', price: 1},
    {id: 'fini_chicle', name: 'Fini Chicle Bubblegum', category: 'candy', price: 1},
    {id: 'lollipop', name: 'Lollipop', category: 'candy', price: 3},
    {id: 'weird_eye', name: 'Weird Eye Candy', category: 'candy', price: 4},
    {id: 'weird_strawberry', name: 'Weird Strawberry Candy', category: 'candy', price: 4},
    {id: 'weird_yellow', name: 'Weird Yellow Candy', category: 'candy', price: 4},
    {id: 'hop_siup', name: 'Hop Siup Candies', category: 'candy', price: 3},
    {id: 'fini_berries', name: 'Fini Roller Berries', category: 'candy', price: 5},
    {id: 'fini_watermelon', name: 'Fini Roller Watermelon', category: 'candy', price: 5},
    {id: 'fini_mix', name: 'Fini Roller Mix', category: 'candy', price: 5},
    {id: 'fini_strawberry', name: 'Fini Roller Strawberry', category: 'candy', price: 5},
    {id: 'fini_shooter', name: 'Fini Shooter', category: 'candy', price: 5},
    {id: 'mentos', name: 'Mentos', category: 'candy', price: 4},

    // Salty
    {id: 'pain_chocolat', name: 'Pain au Chocolat', category: 'salty', price: 4},
    {id: 'chausson', name: 'Chausson', category: 'salty', price: 5},
    {id: 'turkey_sandwich', name: 'Smoked Turkey Sandwich', category: 'salty', price: 15},
    {id: 'chicken_sandwich', name: 'Chicken Sandwich', category: 'salty', price: 20},
    {id: 'meat_sandwich', name: 'Minced Meat Sandwich', category: 'salty', price: 20},
    {id: 'toasts', name: 'Toasts', category: 'salty', price: 7},
    {id: 'briwat', name: 'Briwat', category: 'salty', price: 7},
    {id: 'small_pizza', name: 'Small Pizza', category: 'salty', price: 5}
];